### ISSUE TITLE
New invariant configuration

### ISSUE THREAD

**Issue by maweki** [maweki/ha-decl-tk#1]
So we would probably like to do something like this

```yaml
decl_tk:
  invariants:
    - name: Light 2 follows leader
      invariant: "states('light.light1') == states('light.light2')"
      no_action:
        - light.light1
```
